name: CI

on:
  pull_request:
  push:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Run lint
        run: pre-commit run --all-files
      - name: Install dependencies
        run: pip install -r api/requirements.txt
      - name: Run tests
        run: pytest
